'use strict';
const $=id=>document.getElementById(id);
const M=window.CanopyModel;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={files:[],templates:{},root:''}, rows=[], localRows=[], walkEtag=null, current=null, tab='overview', demo=false, room='', zone='', through='', selectedSeries='', selection=[], loaded=false, busy=false;
const displayTime=t=>t==null?'Time not recorded':new Date(t).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'});
const shortTime=t=>t==null?'Unknown time':new Date(t).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const number=n=>new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(n);
const flagged=r=>['moderate','high'].includes((r.severity||'').trim().toLowerCase());
const zoneName=r=>r.zone?.trim()?r.zone:'Unspecified zone';
const cmpTime=(a,b)=>(b.time??-Infinity)-(a.time??-Infinity);
function note(message,error=false){$('notice').textContent=message;$('notice').hidden=!message;$('notice').classList.toggle('is-error',error);}
async function api(path,data){const res=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Desk-Token':state.token},body:JSON.stringify(data)}:{});const value=await res.json();if(!res.ok)throw Error(value.error||res.statusText);return value;}
function dirty(){return current&&!demo&&($('text').value!==current.text||$('filename').value!==current.name);}
function canLeave(){return !dirty()||window.confirm('This record has unsaved changes. Leave without saving? Export the draft first if you want to keep it.');}
function options(element,items,value,placeholder){element.innerHTML=(placeholder?`<option value="">${esc(placeholder)}</option>`:'')+items.map(i=>`<option value="${esc(i.value)}">${esc(i.label)}</option>`).join('');element.value=value;}
async function refresh(){
  $('refresh').disabled=true;
  try{const next=await api('/api/state');let nextRows=[],etag=null;
    let csvError='';if(next.files.some(f=>f.name==='crop-walk.csv')){try{const f=await api('/api/file?name=crop-walk.csv');etag=f.etag;nextRows=M.observations(f.text);}catch(error){csvError='Crop walk could not be read: '+error.message+' Open crop-walk.csv in Library to repair it. Other records remain available.';}}
    if(walkEtag!==etag&&!demo){selection=[];}state=next;localRows=nextRows;walkEtag=etag;loaded=true;
    if(!demo)rows=localRows;
    $('root').textContent=state.root;$('load-error').hidden=true;renderAll();if(csvError)note(csvError,true);return !csvError;
  }catch(e){$('load-error-text').textContent='Could not refresh local records. '+e.message+' Your open draft is preserved.';$('load-error').hidden=false;$('context').textContent='RECORDS UNAVAILABLE';if(!loaded){$('hero-summary').innerHTML='<strong>Connection unavailable</strong><span>Retry when the local workspace is running.</span>';$('zone-field').innerHTML='<p class="empty-message">Your records could not be loaded.</p>';$('scope-summary').textContent='Waiting for local records';}return false;}
  finally{$('refresh').disabled=false;}
}
function scoped(includeZone=true){const cutoff=through?Date.parse(through+'T23:59:59.999Z'):Infinity;return rows.filter(r=>(!room||r.room===room)&&(!through||(r.time!==null&&r.time<=cutoff))&&(!includeZone||!zone||zoneName(r)===zone));}
function renderScopes(){const rooms=M.rooms(rows);if(room&&!rooms.includes(room))room='';options($('room-filter'),rooms.map(r=>({value:r,label:r})),room,'All recorded rooms');const dates=[...new Set(rows.filter(r=>r.time!==null&&(!room||r.room===room)).map(r=>new Date(r.time).toISOString().slice(0,10)))].sort().reverse();if(through&&!dates.includes(through))through='';options($('date-filter'),dates.map(d=>({value:d,label:d+' · UTC'})),through,'Latest recorded');if(zone&&!M.zones(scoped(false)).includes(zone))zone='';const s=M.summarize(scoped());$('scope-summary').textContent=`${s.count} observation${s.count===1?'':'s'}${zone?' · '+zone:''} · ${through?'through selected date':'all recorded time'}${rows.some(r=>r.time===null)?' · undated entries '+(through?'excluded':'retained'):''}`;$('clear-scope').hidden=!room&&!zone&&!through;}
function renderAll(){
  renderScopes();$('context').textContent=demo?'FICTIONAL EXAMPLE / SEPTEMBER 2026':'YOUR LOCAL FIELD STATION';$('demo-banner').hidden=!demo;$('example').textContent=demo?'Return to my records ↗':'Explore example ↗';
  const s=M.summarize(scoped());const countRooms=M.rooms(scoped()).length;
  $('hero-summary').innerHTML=`<div><span class="large-number">${String(s.count).padStart(2,'0')}</span><span>recorded observation${s.count===1?'':'s'}</span></div><div class="summary-facts"><span><b>${countRooms}</b> room${countRooms===1?'':'s'} in view</span><span><b>${s.flagged}</b> reported concerns</span><small>${s.latest!==null?'Latest · '+esc(displayTime(s.latest)):'Your next observation starts the picture.'}</small></div>`;
  renderZones();renderAttention();renderChart();renderContinuity();renderTrail();renderList();
}
function renderZones(){
 const scopedRows=scoped(false), rooms=M.rooms(scopedRows);
 $('all-zones').hidden=!zone;
 if(!scopedRows.length){$('zone-field').innerHTML=`<div class="empty-canopy"><div class="empty-orbit" aria-hidden="true"><span>?</span></div><div><span class="eyebrow">A ROOM IS MORE THAN A READING</span><h3>${rows.length?'No observations in this view.':'Give your canopy a point of view.'}</h3><p>${rows.length?'Change the room or date to restore the wider picture.':'Record a location, a condition, and how you know it. Each crop walk builds a picture you can return to.'}</p><button class="primary" data-capture>Record your first observation</button><button class="text-button" data-example>Explore a populated example ↗</button></div></div>`;bindActions($('zone-field'));return;}
 $('zone-field').innerHTML=(scopedRows.some(r=>!r.room?.trim())?'<p class="coverage-note">'+scopedRows.filter(r=>!r.room?.trim()).length+' observations have no room recorded. Find their source context in Observations.</p>':'')+rooms.map(name=>{const rr=scopedRows.filter(r=>r.room===name);return `<div class="room-cluster"><div class="room-label"><span>${esc(name)}</span><small>${rr.length} observations</small></div><div class="zones">${M.zones(rr).map(z=>{const zr=rr.filter(r=>zoneName(r)===z).sort(cmpTime),s=M.summarize(zr),last=zr[0];return `<button class="zone ${zone===z?'selected':''} ${s.flagged?'has-concern':''}" data-zone="${esc(z)}" data-room="${esc(name)}" aria-pressed="${zone===z&&room===name}"><span class="zone-top"><span class="zone-symbol" aria-hidden="true">${s.flagged?'!':'◌'}</span><span class="zone-count">${s.count} obs.</span></span><strong>${esc(z)}</strong><span class="zone-condition">${esc(last.observed_condition||'Condition not recorded')}</span><span class="zone-bottom">${s.flagged?`${s.flagged} reported concern${s.flagged===1?'':'s'}`:'No moderate / high reports'}<small>${esc(shortTime(s.latest))}</small></span></button>`;}).join('')}</div></div>`;}).join('');
 $('zone-field').querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const off=zone===b.dataset.zone&&room===b.dataset.room;room=b.dataset.room;zone=off?'':b.dataset.zone;selectedSeries='';selection=[];renderAll();const target=[...$('zone-field').querySelectorAll('[data-zone]')].find(x=>x.dataset.zone===b.dataset.zone&&x.dataset.room===b.dataset.room);target?.focus();note(zone?'Showing '+zone+' with its measurements and evidence.':'Showing all zones in '+room+'.');});
}
function renderAttention(){const concerns=scoped().filter(flagged).sort((a,b)=>(b.severity==='high')-(a.severity==='high')||cmpTime(a,b));$('attention-count').textContent=concerns.length;$('attention-list').innerHTML=concerns.length?concerns.slice(0,4).map(r=>`<button class="concern" data-observation="${esc(r.id)}"><span class="concern-meta"><span class="severity ${r.severity==='high'?'high':''}">${esc(r.severity)} · reported</span><time>${esc(shortTime(r.time))}</time></span><strong>${esc(r.observed_condition)}</strong><span>${esc(r.room)} / ${esc(zoneName(r))} <b>↗</b></span></button>`).join(''):`<div class="quiet-state"><span aria-hidden="true">◌</span><h3>${scoped().length?'No moderate or high reports.':'Nothing reported yet.'}</h3><p>${scoped().length?'That describes the records in view. It does not establish crop health.':'Observations reveal what deserves a closer look. Missing records are still an unknown.'}</p></div>`;bindActions($('attention-list'));}
function renderChart(){
 const rs=scoped();if(!room&&M.rooms(rs).length>1){$('series-select').innerHTML='<option>Select one room first</option>';$('series-select').disabled=true;$('series-meta').textContent='';$('chart').innerHTML='<div class="chart-empty"><strong>Start with one room.</strong><span>Choose a room above to compare measurements within the same context.</span></div>';$('chart-points').innerHTML='';return;}
 const series=M.series(rs);$('series-select').disabled=!series.length;if(!series.some(s=>s.key===selectedSeries))selectedSeries=series[0]?.key||'';
 options($('series-select'),series.map(s=>({value:s.key,label:`${s.unit} · ${zoneName(s.rows[0])} · ${s.rows[0].observation_type} · ${s.rows[0].method} · ${s.rows[0].sensor_or_tool} · ${s.rows[0].facility||'facility unspecified'} / ${s.rows[0].crop_id||'crop unspecified'} / ${s.rows[0].stage||'stage unspecified'}`})),selectedSeries,series.length?null:'No dated measurements');
 const chosen=series.find(s=>s.key===selectedSeries);
 if(!chosen){$('series-meta').textContent='';$('chart').innerHTML='<div class="chart-empty"><span class="empty-chart-line" aria-hidden="true">· &nbsp; · &nbsp; · &nbsp; · &nbsp; ·</span><strong>A change needs more than a number.</strong><span>Add a timestamp, unit, method and instrument to give readings their context.</span></div>';$('chart-points').innerHTML='';return;}
 const rr=chosen.rows,first=rr[0],last=rr[rr.length-1],vals=rr.map(r=>Number(r.measurement_value));const delta=vals.at(-1)-vals[0];
 $('series-meta').innerHTML=`<span><strong>${esc(last.measurement_value)} <small>${esc(chosen.unit)}</small></strong><span>latest recorded</span></span><span class="delta">${rr.length>1?(delta>0?'+':'')+number(delta)+' '+esc(chosen.unit)+' across '+rr.length+' readings':'1 reading · no trend yet'}</span><p>${esc(first.method||'Method not recorded')}<br><span>${esc(first.sensor_or_tool||'Tool not recorded')} · ${esc(first.observation_type||'Type not recorded')} · ${esc(zoneName(first))}<br>${esc(first.facility||'Facility not recorded')} · ${esc(first.crop_id||'Crop not recorded')} · ${esc(first.stage||'Stage not recorded')}</span>`;
 const w=Math.max(260,$('chart').clientWidth||760),h=182,left=52,right=25,top=22,bottom=38;let low=Math.min(...vals),high=Math.max(...vals);const pad=(high-low)*.18||Math.max(Math.abs(high)*.02,.5);low-=pad;high+=pad;const start=first.time,end=last.time;const xx=t=>left+(end===start?.5:(t-start)/(end-start))*(w-left-right);const yy=v=>h-bottom-(v-low)/(high-low)*(h-top-bottom);
 let lines=[0,.5,1].map(t=>{const v=low+(high-low)*t,y=yy(v);return `<line x1="${left}" y1="${y}" x2="${w-right}" y2="${y}" class="chart-grid"/><text x="${left-10}" y="${y+4}" text-anchor="end">${number(v)}</text>`;}).join('');
 $('chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Discrete ${esc(chosen.unit)} readings. ${rr.length} observations from ${esc(displayTime(start))} to ${esc(displayTime(end))}. Values are available in buttons below.">${lines}${rr.map(r=>`<circle cx="${xx(r.time)}" cy="${yy(Number(r.measurement_value))}" r="7" class="chart-dot"><title>${esc(r.measurement_value)} ${esc(chosen.unit)} · ${esc(displayTime(r.time))}</title></circle>`).join('')}<text x="${left}" y="${h-6}">${esc(shortTime(start))}</text><text x="${w-right}" y="${h-6}" text-anchor="end">${rr.length>1?esc(shortTime(end)):''}</text></svg>`;
 $('chart-points').innerHTML=rr.map(r=>`<button class="point-button" data-observation="${esc(r.id)}"><strong>${esc(r.measurement_value)} ${esc(r.unit)}</strong><small>${esc(shortTime(r.time))}</small></button>`).join('');bindActions($('chart-points'));
}
function files(){return demo?Object.keys(demoRecords).map(name=>({name})):state.files.filter(f=>(tab==='records'&&$('include-archives').checked)||! /^(history|imports)\//.test(f.name));}
function renderContinuity(){const ff=files().filter(f=>f.name.startsWith('handoffs/'));$('continuity').innerHTML=ff.length?ff.slice(0,3).map(f=>`<button class="handoff-link" data-file="${esc(f.name)}"><span aria-hidden="true">↗</span><span><strong>${esc(fileTitle(f.name))}</strong><small>Native handoff · open the source</small></span></button>`).join(''):`<div class="continuity-empty"><h3>Leave a useful next step.</h3><p>Keep the action, owner, open question and verification condition together in a shift handoff.</p><button class="text-button" data-new="handoffs">Start a handoff ↗</button></div>`;bindActions($('continuity'));}
function renderTrail(){const query=$('observation-search').value.toLowerCase();const trail=scoped().filter(r=>[r.observed_condition,r.observer,r.crop_id,r.sensor_or_tool,r.room,r.zone,r.incident_id].join(' ').toLowerCase().includes(query)).sort(cmpTime);$('observation-trail').innerHTML=trail.length?trail.map(r=>`<article class="trail-entry"><div class="trail-time"><time>${esc(displayTime(r.time))}</time><span>${esc(r.room)}<b>${esc(zoneName(r))}</b></span></div><button class="trail-body" data-observation="${esc(r.id)}"><span class="trail-tags"><span>${esc(r.observation_type||'Unclassified type')}</span><span class="severity ${flagged(r)?'flagged':''}">${esc(r.severity||'unclassified')} · reported</span></span><h3>${esc(r.observed_condition||'Condition not recorded')}</h3><p>${esc(r.observer||'Observer missing')} · ${esc(r.crop_id||'Crop ID missing')} · ${esc(r.stage||'Stage missing')}</p><span class="trail-measure">${r.measurement_value?.trim()?`<strong>${esc(r.measurement_value)} ${esc(r.unit)}</strong> ${esc(r.method||'Method not recorded')}`:'Visual observation · no numeric measurement'} <b>↗</b></span></button><label class="compare-check"><input type="checkbox" data-compare="${esc(r.id)}" ${selection.includes(r.id)?'checked':''}>Compare</label></article>`).join(''):`<div class="large-empty"><h3>${query?'No matching observations.':'Your observation trail starts here.'}</h3><p>${query?'Try a different condition, observer or instrument.':'Record a crop walk to preserve location, time, evidence and the person who saw it.'}</p><button class="primary" data-capture>Record observation</button></div>`;bindActions($('observation-trail'));
 $('observation-trail').querySelectorAll('[data-compare]').forEach(c=>c.onchange=()=>{if(c.checked&&selection.length>=2){c.checked=false;note('Two observations are selected. Clear one to choose another.');return;}selection=c.checked?[...selection,c.dataset.compare]:selection.filter(id=>id!==c.dataset.compare);renderCompareTray();});renderCompareTray();}
function renderCompareTray(){$('compare-tray').hidden=!selection.length;$('compare-count').textContent=selection.length+' of 2 observations selected';$('compare').disabled=selection.length!==2;}
function detailFields(r){const fields=[['Facility',r.facility],['Recorded at',r.timestamp],['Room / zone',`${r.room||'Not recorded'} / ${zoneName(r)}`],['Crop / stage',`${r.crop_id||'Not recorded'} / ${r.stage||'Not recorded'}`],['Observed by',r.observer],['Type',r.observation_type],['Reported severity',r.severity],['Measurement',r.measurement_value?.trim()?`${r.measurement_value} ${r.unit}`:''],['Method',r.method],['Sensor / tool',r.sensor_or_tool],['Distribution',r.distribution],['Plant / sample',r.plant_or_sample],['Action already taken',r.action_taken],['Incident reference',r.incident_id],['Photo / record',r.photo_or_record],['Notes',r.notes]];return `<dl class="evidence-fields">${fields.map(([k,v])=>`<div><dt>${k}</dt><dd${!v?' class="missing"':''}>${esc(v||'Not recorded')}</dd></div>`).join('')}</dl>`;}
function openObservation(id){const r=rows.find(r=>r.id===id);if(!r)return;$('observation-title').textContent=r.observed_condition||'Observation';let photo='';if(!demo&&/^photos\/[a-zA-Z0-9_.-]+$/.test(r.photo_or_record||''))photo=`<a href="/${esc(r.photo_or_record)}" target="_blank" rel="noopener"><img class="evidence-photo" src="/${esc(r.photo_or_record)}" alt="Attached observation evidence; open original"></a>`;$('observation-detail').innerHTML=`<p class="source-line">${demo?'Fictional example':'crop-walk.csv'} · row ${Number(r.id)+2} · original field values</p>${photo}${detailFields(r)}<p class="evidence-note">A recorded severity is the observer’s assessment. This view does not confirm a diagnosis or authorize a change.</p>`;$('observation-dialog').showModal();}
function compare(){const pair=selection.map(id=>rows.find(r=>r.id===id));if(pair.some(r=>!r)||pair.length!==2)return;const [a,b]=pair;const keys=['facility','room','zone','crop_id','stage','observation_type','unit','method','sensor_or_tool'];const compatible=[a,b].every(r=>['observation_type','unit','method','sensor_or_tool'].every(k=>r[k]?.trim()))&&keys.every(k=>(a[k]||'')===(b[k]||''))&&[a,b].every(r=>r.measurement_value?.trim()&&Number.isFinite(Number(r.measurement_value)));const delta=compatible?Number(b.measurement_value)-Number(a.measurement_value):null;$('comparison').innerHTML=`<p class="comparison-note">${compatible?`B − A: <strong>${delta>0?'+':''}${number(delta)} ${esc(a.unit)}</strong>. Matching recorded facility, room, zone, crop, stage, unit, method and tool. A difference is not a diagnosis.`:'Measurement contexts differ or a numeric reading is missing. Read the source context before comparing values.'}</p><div class="comparison-grid">${pair.map((r,i)=>`<section><span class="eyebrow">${i?'B':'A'} / ${esc(displayTime(r.time))}</span><h3>${esc(r.observed_condition)}</h3>${detailFields(r)}</section>`).join('')}</div>`;$('compare-dialog').showModal();}
const fileTitle=name=>name.split('/').pop().replace(/\.[^.]+$/,'').replace(/[-_]/g,' ');
function renderList(){const q=$('record-search').value.toLowerCase();const ff=files().filter(f=>(tab==='records'||f.name.startsWith(tab+'/'))&&f.name.toLowerCase().includes(q));$('file-list').innerHTML=ff.length?ff.map(f=>`<button class="file-link ${current?.name===f.name?'selected':''}" data-file="${esc(f.name)}"><small>${esc(f.name.split('/')[0])}</small><strong>${esc(fileTitle(f.name))}</strong><span>↗</span></button>`).join(''):`<p class="empty-message">${q?'No matching filenames.':'No records here yet.'}</p>`;bindActions($('file-list'));}
async function openRecord(name){if(!canLeave())return;try{const f=demo?{name,text:demoRecords[name],etag:null}:await api('/api/file?name='+encodeURIComponent(name));if(f.text==null)return;if(!['records','incidents','handoffs'].includes(tab))switchTab(name.startsWith('handoffs/')?'handoffs':'records',true);current=f;showRecord();renderList();$('record-title').scrollIntoView({block:'nearest',behavior:'instant'});}catch(e){note(e.message,true);}}
function renderReading(text){const host=$('reading');host.innerHTML=text.split(/\r?\n/).map(line=>{const h=line.match(/^(#{1,4})\s+(.+)$/);if(h)return `<h${Math.min(4,h[1].length+1)}>${esc(h[2])}</h${Math.min(4,h[1].length+1)}>`;if(/^[-*]\s/.test(line))return `<p class="record-bullet">${esc(line.slice(2))}</p>`;return line?`<p>${esc(line)}</p>`:'<div class="paragraph-gap"></div>';}).join('');}
function showRecord(){const preserved=!!current&&/^(history|imports)\//.test(current.name);$('empty-record').hidden=!!current;$('editor').hidden=!current;if(!current)return;$('filename').value=current.name;$('text').value=current.text;$('record-title').textContent=current.name;renderReading(current.text);$('native-editor').open=current.etag===null&&!demo;$('save').disabled=demo||preserved;$('filename').readOnly=demo||preserved;$('text').readOnly=demo||preserved;$('save-hint').textContent=demo?'Read-only fictional example; your records are unchanged.':preserved?'Preserved original or revision — read-only. Export to work from a copy.':'Checks for changes made since you opened this file.';$('dirty-state').textContent='';}
function switchTab(value,skipGuard=false){if(!skipGuard&&!canLeave())return false;note('');if(value!==tab){current=null;showRecord();}tab=value;document.body.dataset.view=tab;document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('overview-panel').hidden=tab!=='overview';$('walk-panel').hidden=tab!=='walk';$('library-panel').hidden=!['records','incidents','handoffs'].includes(tab);$('scope-bar').hidden=['records','incidents','handoffs'].includes(tab);const heads={overview:['Read the room.','The crop, its changes, and the evidence behind your next move.'],walk:['Follow the evidence.','Each observation keeps its place, its time, and the person who saw it.'],incidents:['Hold the question open.','Keep explanations, evidence and response boundaries together.'],handoffs:['Make the next shift wiser.','What changed, what remains open, and who takes it from here.'],records:['The memory of the crop.','Native files shared by your field station and your AI collaborator.']};$('page-title').textContent=heads[tab][0];$('page-deck').textContent=heads[tab][1];$('library-title').textContent={incidents:'Investigations in context.',handoffs:'The next move, with its context.',records:'Working knowledge.'}[tab]||'';$('library-eyebrow').textContent=tab==='records'?'NATIVE RECORDS':tab.toUpperCase();$('new').textContent='＋ New '+({incidents:'incident',handoffs:'handoff'}[tab]||'room runbook');$('new-batch').hidden=tab!=='records';$('archives-label').hidden=tab!=='records';renderList();if(tab==='overview')renderChart();return true;}
function newRecord(kind){if(!loaded){note('Wait for local records to load.',true);return;}if(!canLeave())return;if(demo){demo=false;rows=localRows;resetScope();renderAll();}const t=kind==='batches'?'records':kind==='rooms'?'records':kind;switchTab(t,true);current={name:kind+'/untitled-'+Date.now()+'.md',text:state.templates[kind]||'# Record\n',etag:null};showRecord();$('filename').focus();note('Draft started. Fill in the source record and save when ready.');}
async function saveRecord(){if(!current||demo||busy||/^(history|imports)\//.test(current.name))return;busy=true;$('save').disabled=true;try{const name=$('filename').value.trim(),text=$('text').value;const result=await api('/api/save',{name,text,etag:name===current.name?current.etag:null});current={name,text,etag:result.etag};showRecord();await refresh();note('Saved native record.');}catch(e){note(e.message+' Your draft is still here; export it before reopening.',true);}finally{busy=false;$('save').disabled=demo;}}
function resetScope(){room='';zone='';through='';selection=[];selectedSeries='';}
function toggleExample(force){if(!canLeave())return;demo=force??!demo;rows=demo?demoRows:localRows;current=null;resetScope();if(demo)room='Glasshouse A';showRecord();switchTab('overview',true);renderAll();note(demo?'':'Returned to your local records.');}
function capture(){if(!loaded)return note('Local records must load before capture.',true);if(demo)toggleExample(false);const form=$('walk-form');if(!form.elements.observed_at.value){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());form.elements.observed_at.value=d.toISOString().slice(0,16);}if(!form.elements.room.value)form.elements.room.value=room;if(!form.elements.zone.value&&zone)form.elements.zone.value=zone==='Unspecified zone'?'':zone;$('capture-error').hidden=true;$('capture-dialog').showModal();}
function bindActions(host){host.querySelectorAll('[data-observation]').forEach(b=>b.onclick=()=>openObservation(b.dataset.observation));host.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openRecord(b.dataset.file));host.querySelectorAll('[data-capture]').forEach(b=>b.onclick=capture);host.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>toggleExample(true));host.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>newRecord(b.dataset.new));}
async function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read file.'));reader.readAsDataURL(file);});}
$('walk-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('record-observation').disabled=true;$('capture-error').hidden=true;try{const row=Object.fromEntries(new FormData(e.target));row.timestamp=new Date(row.observed_at).toISOString();delete row.observed_at;if(row.measurement_value.trim()&&(!row.unit.trim()||!row.method.trim()||!row.sensor_or_tool.trim())){document.querySelector('.measurement-fields').open=true;throw Error('Measurements need a unit, method and sensor/tool. Your observation has been kept.');}const photo=$('photo').files[0];if(photo&&photo.size>8000000)throw Error('Photo limit is 8 MB. Choose a smaller image.');await api('/api/walk',{row,etag:walkEtag,photo:photo?{filename:photo.name,data:await fileBase64(photo)}:null});e.target.reset();$('capture-dialog').close();resetScope();room=row.room;await refresh();switchTab('walk');note('Observation saved to crop-walk.csv.');}catch(err){$('capture-error').textContent=err.message;$('capture-error').hidden=false;if(/changed/i.test(err.message)){await refresh();$('capture-error').textContent+=' The latest file has been reloaded. Review your retained observation and submit again.';}}finally{busy=false;$('record-observation').disabled=false;}};
$('import').onchange=async e=>{const file=e.target.files[0];try{if(!file)return;if(!canLeave())return;if(demo)toggleExample(false);if(file.size>8000000)throw Error('Record limit is 8 MB.');const text=await file.text(),safeName=file.name.replace(/[^A-Za-z0-9_. -]/g,'_');let name=(['incidents','handoffs'].includes(tab)?tab:'rooms')+'/'+safeName;
 if(safeName.toLowerCase()==='crop-walk.csv'){if(state.files.some(f=>f.name==='crop-walk.csv'))throw Error('A crop-walk.csv already exists. Open it in Library to reconcile the records without overwriting observations.');name='crop-walk.csv';}
 const result=await api('/api/save',{name,text,etag:null,import:true,original:await fileBase64(file)});if(!['records','incidents','handoffs'].includes(tab))switchTab('records',true);current={name,text,etag:result.etag};showRecord();await refresh();note('Imported. Original bytes preserved under imports.');}catch(err){note(err.message,true);}finally{e.target.value='';}};
$('export').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([$('text').value],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download=$('filename').value.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);note('Exported the current draft, including unsaved edits.');};$('print').onclick=()=>window.print();
$('save').onclick=saveRecord;$('text').oninput=()=>{renderReading($('text').value);$('dirty-state').textContent=dirty()?'· Unsaved changes':'';};$('filename').oninput=()=>{$('dirty-state').textContent=dirty()?'· Unsaved changes':'';};
$('new').onclick=()=>newRecord(['incidents','handoffs'].includes(tab)?tab:'rooms');$('new-batch').onclick=()=>newRecord('batches');
$('include-archives').onchange=renderList;$('record-search').oninput=renderList;$('observation-search').oninput=renderTrail;
$('capture').onclick=capture;$('example').onclick=()=>toggleExample();$('leave-example').onclick=()=>toggleExample(false);
$('room-filter').onchange=e=>{note('');room=e.target.value;zone='';selectedSeries='';selection=[];renderAll();};$('date-filter').onchange=e=>{note('');through=e.target.value;selection=[];renderAll();};$('all-zones').onclick=()=>{note('');zone='';renderAll();};$('clear-scope').onclick=()=>{note('');resetScope();renderAll();};$('series-select').onchange=e=>{selectedSeries=e.target.value;renderChart();};
$('compare').onclick=compare;$('clear-compare').onclick=()=>{selection=[];renderTrail();};
$('refresh').onclick=()=>refresh().then(ok=>{if(ok)note('Local records refreshed.');});$('retry').onclick=refresh;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go));document.querySelector('.brand').onclick=e=>{e.preventDefault();switchTab('overview');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
window.addEventListener('beforeunload',e=>{if(dirty()||$('walk-form').elements.observed_condition.value){e.preventDefault();e.returnValue='';}});
let savedSkin='';try{savedSkin=localStorage.getItem('canopy-skin')||'';}catch{};savedSkin=({sodium:'lampblack',sunprint:'clearspan'})[savedSkin]||savedSkin;$('skin').value=['understory','lampblack','clearspan'].includes(savedSkin)?savedSkin:'understory';document.body.dataset.skin=$('skin').value;$('skin').onchange=()=>{document.body.dataset.skin=$('skin').value;try{localStorage.setItem('canopy-skin',$('skin').value);}catch{};};
const demoRows=[
 ['2026-09-22T08:00:00-05:00','Glasshouse A','West canopy','environment','26.1','°C','low','Leaf edges slightly curled on sampled west-side plants.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-22T08:12:00-05:00','Glasshouse A','East canopy','environment','25.7','°C','unclassified','Paired east-side sample; no visible curl recorded.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-22T11:00:00-05:00','Glasshouse A','West canopy','environment','26.8','°C','moderate','Leaf curl remains visible in the west sample.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-22T11:10:00-05:00','Glasshouse A','East canopy','environment','26.0','°C','unclassified','Repeat comparison observation from east-side plants.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-22T14:00:00-05:00','Glasshouse A','West canopy','environment','27.2','°C','moderate','West sample still differs from the east sample. Cause unresolved.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-22T14:15:00-05:00','Glasshouse A','Entry bench','visual','','','unclassified','Reference plants photographed; no paired measurement recorded.','',''],
 ['2026-09-23T08:00:00-05:00','Glasshouse A','West canopy','environment','26.4','°C','moderate','Curl still present on marked sample plants; retain paired observations.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-23T08:10:00-05:00','Glasshouse A','East canopy','environment','25.8','°C','unclassified','East comparison sample photographed again.','Canopy-height spot reading','Probe A · calibration not supplied'],
 ['2026-09-23T08:30:00-05:00','Nursery B','North bench','visual','','','low','Two sample leaves show edge discoloration; extent not established.','',''],
 ['2026-09-23T08:40:00-05:00','Nursery B','South bench','visual','','','unclassified','Comparison sample marked for the next walk.','','']
].map((a,i)=>({id:String(i),timestamp:a[0],time:Date.parse(a[0]),facility:'Fictional demonstration',room:a[1],zone:a[2],observation_type:a[3],measurement_value:a[4],unit:a[5],severity:a[6],observed_condition:a[7],method:a[8],sensor_or_tool:a[9],observer:'Example shift lead',crop_id:a[1]==='Glasshouse A'?'EXAMPLE-09':'EXAMPLE-N2',stage:a[1]==='Glasshouse A'?'Early flower':'Vegetative',plant_or_sample:'Marked comparison sample',distribution:'Sample only; whole-room extent unknown',action_taken:'Observation recorded; no equipment change.',incident_id:a[2]==='West canopy'?'EXAMPLE-WEST':'',photo_or_record:'',notes:'Fictional data. No approved target supplied.'}));
const demoRecords={
 'rooms/glasshouse-a.md':'# Glasshouse A · room context\n\nFictional example — unsaved.\n\nRoom: Glasshouse A\nBatch: EXAMPLE-09\nStage: Early flower\nOwner: Example shift lead\n\n## What we know\nWest canopy observations differ from paired east-side samples. These are spot readings, not a continuous sensor trace.\n\n## What remains open\nProbe calibration, whole-room distribution, and the cause of the visible difference have not been established.\n\n## Response boundary\nNo approved target supplied. No setpoint change authorized. Preserve paired evidence for review.',
 'incidents/west-canopy-observation.md':'# West canopy · question still open\n\nFictional example — unsaved.\n\nStatus: Investigating\nOwner: Example shift lead\nRoom: Glasshouse A\n\n## Evidence\nRecorded west-side leaf curl and canopy-height spot readings. Paired east-side observations retain a comparison.\n\n## Competing explanations\nObservation or instrument differences and real spatial variation remain open. These records do not establish cause.\n\n## Next action\nRetain instrument context and the affected/unaffected comparison for an accountable review.\n\n## Authority\nDiagnostic observation only; no corrective action authorized.',
 'handoffs/glasshouse-a-next-walk.md':'# Glasshouse A · next crop walk\n\nFictional example — unsaved.\n\nOwner: Example shift lead\nStatus: Provisional\n\n## Carry forward\nWest-side sample remains visibly different. Read the observation trail before interpreting the latest temperature.\n\n## Next action\nRevisit the marked west and east sample plants, retain location and instrument details, and record any change in distribution.\n\n## Verify / reopen\nReopen the workup if observations progress, distribution changes, or new evidence contradicts the working account.\n\n## Authority\nNo equipment setting changed or approved.'
};
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(loaded&&tab==='overview')renderChart();},100);});
document.body.dataset.view=tab;refresh();
